/** @format */

export const colonLabelPattern =
	/^([A-Za-z][A-Za-z0-9 ._'&-]{0,39}):\s*(.*)$/;
export const standaloneLabelPattern = /^[A-Za-z][A-Za-z0-9 ._'&-]{0,39}$/;
export const noticePattern =
	/^(?:content\s+(?:notice|warning)|warning|viewer\s+discretion|disclaimer|trigger\s+warning)\s*:/i;
export const metadataPattern =
	/^(?:FILE|CASE|DOCUMENT|DOC|RECORD|ID|DATE|VERSION|DRAFT|REVISION|SLUG|AUTHOR|PUBLISHED|UPDATED|ISBN|ATTENDEES?|AGENDA|ACTION\s+ITEMS?|DECISIONS?)\s*:/i;
export const sceneHeadingPattern = /^(?:INT\.|EXT\.|INT\/EXT\.|I\/E\.)\s*/i;
export const stageSceneHeadingPattern = /^SCENE\b/i;
export const transitionPattern =
	/^(?:FADE\s+(?:IN|OUT)|CUT\s+TO|DISSOLVE\s+TO|SMASH\s+CUT\s+TO|MATCH\s+CUT\s+TO|WIPE\s+TO|BACK\s+TO|BLACKOUT|END\s+CREDITS)(?::|\.)?$/i;
export const displayHeadingPattern =
	/^(?:EPISODE|TITLE|TITLE\s+CARD|SUPER|ON\s+SCREEN|CHYRON|LOWER\s+THIRD)\b/i;
export const sectionHeadingPattern =
	/^(?:SECTION|CHAPTER|ACT|SCENE|PART|FIELD\s+EDITION|BEST\s+PRACTICE|POST[- ]ACTION\s+REVIEW|INTRODUCTION|CONCLUSION|OVERVIEW|SUMMARY|APPENDIX|ABSTRACT|METHODS?|METHODOLOGY|RESULTS|REFERENCES|PROFESSIONAL\s+SUMMARY|WORK\s+EXPERIENCE|EMPLOYMENT\s+EXPERIENCE|EDUCATION|SKILLS|CERTIFICATIONS|QUALIFICATIONS|PROLOGUE|EPILOGUE|DEDICATION)\b/i;
export const structuralLabelPattern =
	/^(?:FILE|CASE|DOCUMENT|DOC|RECORD|ID|DATE|VERSION|DRAFT|REVISION|SLUG|AUTHOR|PUBLISHED|UPDATED|ISBN|ATTENDEES?|AGENDA|ACTION\s+ITEMS?|DECISIONS?|EPISODE|TITLE|SECTION|CHAPTER|ACT|SCENE|PART|FIELD\s+EDITION|BEST\s+PRACTICE|POST[- ]ACTION\s+REVIEW|ABSTRACT|METHODS?|METHODOLOGY|RESULTS|REFERENCES|PROFESSIONAL\s+SUMMARY|WORK\s+EXPERIENCE|EMPLOYMENT\s+EXPERIENCE|EDUCATION|SKILLS|CERTIFICATIONS|QUALIFICATIONS|PROLOGUE|EPILOGUE|DEDICATION)\b/i;
export const commonRolePattern =
	/^(?:NARRATOR|HOST|GUEST|EDITOR|INTERVIEWER|REPORTER|ANNOUNCER|MODERATOR|VOICE|V\.O\.|SPEAKER)(?:\s+\d+)?$/i;
